---
title: "Tidy Table Practice"
author: "Brett Stacy"
date: "2024-05-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Practice Tidytable Commands

This .Rmd is simply a place where I can practice and take notes on tidytable commands as I see fit. I hope to document commands from swo and surveyISS as I learn them. 

```{r}
library(tidytable)
```

## Simple examples from the package readme

```{r}
df <- data.table(x = 1:3, y = 4:6, z = c("a", "a", "b")) # you have to start with a data.table before you can perform tidytable commands on it

df %>% select(x, y) # selects the specified variables

df %>% filter(x <= 2) # only keeps the variable entries where the condition is met
df %>% filter(x < 2, y < 5) # for multiple conditions

df %>% mutate(inv_x = 1/x) -> df # add another variable as a function of an existing one and redefine df with it

df %>% arrange(inv_x) # rearrange df by ordering everything according to inv_x from small to big


```


